### ISSUE TITLE
Error in Statamic beta 38

### ISSUE THREAD

**Issue by mikemartin** [aryehraber/statamic-font-awesome#7]
Hey @aryehraber!

After installing the Statamic Beta 38 I'm now getting this error with your addon. Could be related to their major Blueprint restructuring outlined here: 
https://github.com/statamic/cms/pull/2092
```
[previous exception] [object] (Error(code: 0): Call to a member function value() on null at /Users/mike/Sites/rezzz/vendor/aryehraber/statamic-font-awesome/src/FontAwesomeTags.php:34)
[stacktrace]
#0 /Users/mike/Sites/rezzz/vendor/aryehraber/statamic-font-awesome/src/FontAwesomeTags.php(22): AryehRaber\\FontAwesome\\FontAwesomeTags->output(NULL)
#1 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Tags/Tags.php(137): AryehRaber\\FontAwesome\\FontAwesomeTags->wildcard('icon')
#2 [internal function]: Statamic\\Tags\\Tags->__call('icon', Array)
#3 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func(Array)
#4 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'font_awesome', Array, '', Array)
#5 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(573): call_user_func_array(Array, Array)
#6 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(338): Statamic\\View\\Antlers\\Parser->parseCallbackTags('            <di...', Array)
#7 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(289): Statamic\\View\\Antlers\\Parser->parseLoopInstance('            <di...', Array)
#8 [internal function]: Statamic\\View\\Antlers\\Parser->Statamic\\View\\Antlers\\{closure}(Array, 0)
#9 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#10 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(290): Illuminate\\Support\\Collection->map(Object(Closure))
#11 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(224): Statamic\\View\\Antlers\\Parser->parseLoopVariables('<article class=...', Array)
#12 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(176): Statamic\\View\\Antlers\\Parser->parseVariables('<article class=...', Array)
#13 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(131): Statamic\\View\\Antlers\\Parser->parse('<article class=...', Array)
#14 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\\View\\Antlers\\Parser->parseView('/Users/mike/Sit...', '<article class=...', Array)
#15 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/mike/Sit...', Array)
#16 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#17 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#18 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Tags/Partial.php(19): Illuminate\\View\\View->render()
#19 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Tags/Tags.php(137): Statamic\\Tags\\Partial->wildcard('sections/featur...')
#20 [internal function]: Statamic\\Tags\\Tags->__call('sections/featur...', Array)
#21 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func(Array)
#22 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'partial', Array, '', Array)
#23 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(573): call_user_func_array(Array, Array)
#24 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(338): Statamic\\View\\Antlers\\Parser->parseCallbackTags('      {{ partia...', Array)
#25 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(289): Statamic\\View\\Antlers\\Parser->parseLoopInstance('      {{ partia...', Array)
#26 [internal function]: Statamic\\View\\Antlers\\Parser->Statamic\\View\\Antlers\\{closure}(Array, 1)
#27 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#28 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(290): Illuminate\\Support\\Collection->map(Object(Closure))
#29 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(224): Statamic\\View\\Antlers\\Parser->parseLoopVariables('{{ sections }}\
...', Array)
#30 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(176): Statamic\\View\\Antlers\\Parser->parseVariables('{{ sections }}\
...', Array)
#31 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(131): Statamic\\View\\Antlers\\Parser->parse('{{ sections }}\
...', Array)
#32 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\\View\\Antlers\\Parser->parseView('/Users/mike/Sit...', '{{ sections }}\
...', Array)
#33 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/mike/Sit...', Array)
#34 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#35 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#36 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Tags/Partial.php(19): Illuminate\\View\\View->render()
#37 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Tags/Tags.php(137): Statamic\\Tags\\Partial->wildcard('sections')
#38 [internal function]: Statamic\\Tags\\Tags->__call('sections', Array)
#39 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func(Array)
#40 [internal function]: Statamic\\View\\Antlers\\Engine::renderTag(Object(Statamic\\View\\Antlers\\Parser), 'partial', Array, '', Array)
#41 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(573): call_user_func_array(Array, Array)
#42 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(178): Statamic\\View\\Antlers\\Parser->parseCallbackTags('<div class=\"rel...', Array)
#43 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Parser.php(131): Statamic\\View\\Antlers\\Parser->parse('{{ partial:home...', Array)
#44 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\\View\\Antlers\\Parser->parseView('/Users/mike/Sit...', '{{ partial:home...', Array)
#45 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/View.php(139): Statamic\\View\\Antlers\\Engine->get('/Users/mike/Sit...', Array)
#46 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#47 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#48 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/View/View.php(74): Illuminate\\View\\View->render()
#49 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Http/Responses/DataResponse.php(144): Statamic\\View\\View->render()
#50 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Http/Responses/DataResponse.php(45): Statamic\\Http\\Responses\\DataResponse->contents()
#51 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Structures/Page.php(289): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#52 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(744): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#53 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(731): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#54 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#55 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Http/Middleware/Localize.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#68 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Retrieve->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#77 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#78 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#79 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#80 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#81 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/mike/Sites/rezzz/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/mike/Sites/rezzz/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#92 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#93 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 /Users/mike/Sites/rezzz/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /Users/mike/Sites/rezzz/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#97 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#98 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#99 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#100 /Users/mike/Sites/rezzz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#101 /Users/mike/Sites/rezzz/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#102 /Users/mike/.composer/vendor/laravel/valet/server.php(191): require('/Users/mike/Sit...')
#103 {main}
"} 
```

**Comment by aryehraber** [comment]
Thanks for the heads up @mikemartin! Will try and take a look this week.

**Comment by mikemartin** [comment]
Hey @aryehraber 
False alarm. This was an issue with an entries fieldtype in my blueprint.
