### ISSUE TITLE
Unable to use Route:cache command - Unable to prepare route [cp/fontawesome-icons] for serialization. Uses Closure.

### ISSUE THREAD

**Issue by aadind** [aryehraber/statamic-font-awesome#9]
Hello there, 

when i try to cache the routes in my laravel app, this is what I'm getting: 

```
[2020-11-04 11:01:50] local.ERROR: Unable to prepare route [cp/fontawesome-icons] for serialization. Uses Closure. {"exception":"[object] (LogicException(code: 0): Unable to prepare route [cp/fontawesome-icons] for serialization. Uses Closure. at E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php:1150)
[stacktrace]
#0 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\RouteCacheCommand.php(62): Illuminate\\Routing\\Route->prepareForSerialization()
#1 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Foundation\\Console\\RouteCacheCommand->handle()
#2 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#4 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(134): Illuminate\\Container\\Container->call(Array)
#7 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\symfony\\console\\Command\\Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#8 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\symfony\\console\\Application.php(920): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\symfony\\console\\Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\RouteCacheCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\symfony\\console\\Application.php(142): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 E:\\Projects\\Special Projects\\SSSUHE\\development\\SSSUHEv3\\please(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 {main}
"} 
```

Using Statamic 3.0.22 . Issue exists in all of my environments and mostly found after upgrading to latest statamic version. But I'm not sure if it was there before.

**Comment by aryehraber** [comment]
Hi @aadind, thanks for reporting this issue! 

I'm open to a PR that moves the [route closure logic](https://github.com/aryehraber/statamic-font-awesome/blob/master/routes/cp.php) to a controller method, otherwise this will likely have to wait until I find some spare time.

**Comment by aadind** [comment]
@aryehraber  oh okay. I will see if my team can come up with something. If a solution is made i will let you know. thanks for the quick response!

**Comment by aryehraber** [comment]
This addon has been replaced by a new version by another dev: 
https://statamic.com/addons/aerni/font-awesome
